column_mappings:
    HouseholdID: hid
    TWSMonth: month
    # TWSWeekday_B01ID: day
    SurveyYear: year
    Settlement2011EW_B04ID: rurality
    HHIncQISEngTS_B01ID: hh_income
    Ten1_B02ID: ownership
    AddressType_B01ID: dwelling
    HHoldNumPeople: hh_size
    # HHoldStruct_B02ID: hh_composition
    # HHoldNumChildren: hh_children
    NumCar: vehicles
    # NumBike: hh_bikes
    # NumMCycle: hh_motorcycles
    # BlueBdg_B01ID: disabled
    # NumLicHolders: num_license_holders
    W3: weight


dwelling:
    1: house
    2: house
    3: house
    4: house
    5: flat
    6: flat
    7: flat
    8: other
    -8: unknown
    -9: unknown
    -10: unknown

hh_income:
    1: [0,18000]
    2: [18000,26000]
    3: [26000,36000]
    4: [36000,55000]
    5: [55000,200000]
    -8: [0,0]
    -9: [0,0]
    -10: [0,0]

ownership:
    1: owns
    2: rents
    3: other
    -8: unknown
    -9: unknown
    -10: unknown

rurality:
    1: suburban
    2: urban
    3: rural
    4: rural
    5: rural
    -8: unknown
    -10: unknown

hh_composition:
    -8: unknown
    -10: unknown
    1: 1adult
    2: 2adults
    3: 3+adults
    4: single_parent
    5: 2adult_1+child
    6: 3+adult_1+child

disabled:
    1: yes
    2: no
    -8: unknown
    -9: unknown
    -10: unknown

# month:
#     1: january
#     2: february
#     3: march
#     4: april
#     5: may
#     6: june
#     7: july
#     8: august
#     9: september
#     10: october
#     11: november
#     12: december
#     -10: unknown

# day:
#     1: monday
#     2: tuesday
#     3: wednesday
#     4: thursday
#     5: friday
#     6: saturday
#     7: sunday
#     -10: unknown