column_mappings:
    TripID: tid
    JourSeq: seq
    DayID: did
    IndividualID: pid
    HouseholdID: hid
    TripOrigGOR_B02ID: ozone
    TripDestGOR_B02ID: dzone
    TripPurpFrom_B01ID: oact
    TripPurpTo_B01ID: dact
    MainMode_B04ID: mode
    TripStart: tst
    TripEnd: tet
    TripDisIncSW: distance
    W5: trip_weight

mode:
    1: walk
    2: bike
    3: car  # Car/van driver
    4: car  # Car/van driver
    5: car  # Motorcycle
    6: car  # Other private transport
    7: bus  #  Bus in London
    8: bus  # Other local bus
    9: bus  # Non-local bus
    10: rail  # London Underground
    11: rail  # Surface Rail
    12: car  # Taxi/minicab
    13: rail  # Other public transport
    -10: unknown
    -8: unknown

act:
    1: work
    2: work  # In course of work
    3: education
    4: shop  # Food shopping
    5: shop  # Non food shopping
    6: medical  # Personal business medical
    7: other  # Personal business eat/drink
    8: other  # Personal business other
    9: other  # Eat/drink with friends
    10: visit  # Visit friends
    11: other  # Other social
    12: other  # Entertain/ public activity
    13: other  # Sport: participate
    14: home  # Holiday: base
    15: other  # Day trip/just walk
    16: other  # Other non-escort
    17: escort  # Escort home
    18: escort  # Escort work
    19: escort  # Escort in course of work
    20: escort  # Escort education
    21: escort  # Escort shopping/personal business
    22: escort  # Other escort
    23: home  # Home
    -10: unknown
    -8: unknown