[project]
name = "foundata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastexcel>=0.16.0",
    "ipykernel>=7.1.0",
    "ipython>=9.7.0",
    "pip>=25.3",
    "polars>=1.35.2",
]
