persons:
    wtperfin: weight
    aage: age
    dtype: disability
    educ: education
    tcoff: can_wfh
    wkstat: employment_status
    indus: industry
    race: race
    lic: has_license
    relate: relationship_to_respondent

hhs:
    wthhfin: weight
    hhinc: household_income
    resty: residence_type
    homeown: home_ownership
    hhveh: num_vehicles
    hhsize: household_size

vehicles:
    body: veh_type


    
