column_mappings:
    default:
        ppid: pid
        phid: hid
        pagei: age
        psex: sex
        prelrspi: relationship
        pegroup: race

age:
    default:
    0-4: [0, 4]
    5-16: [5, 16]
    17-24: [17, 24]
    25-44: [25, 44]
    45-59: [45, 59]
    60-64: [60, 64]
    65+: [65, 100]

sex:
    default:
        -2: unknown
        -1: unknown
        1: male
        2: female
        5: unknown
        6: unknown

relationship:
    default:
        -2: unknown
        -1: head
        1: spouse/partner
        2: sibling
        3: child
        4: parent
        5: grandparent
        6: grandchild
        7: other
        8: unrelated

race:
    default:
        01 White: white
        02 Mixed, Other and Arab: other
        03 Asian: asian
        04 Black: black
        98 Missing: unknown


