column_mappings:
    default:
        "HOUSEID": "hid"
        # "URBRUR": "rurality"
        # "HBPPOPDN": "population_density"
        "HHFAMINC": "hh_income"
        "HHSIZE": "hh_size"
        "HHVEHCNT": "vehicles"
        "HOMEOWN": "ownership"
        # "LIF_CYC": "life_cycle"
        "TDAYDATE": "date"
        "TRAVDAY": "day"
        # "WRKCOUNT": "num_workers"
        "HH_RACE": "race1"
        "HHR_RACE": "race2"

rurality: {default: {1: 'urban', 2: 'rural'}}

hh_income:
    default:
        -7: [0,0] # 'I prefer not to answer',
        -9: [0,0] # 'Not ascertained',
        -8: [0,0] # 'I do not know',
        1: [0, 10000] #'Less than $10,000',
        2: [10000, 15000] #'$10,000 to $14,999',
        3: [15000, 25000] #'$15,000 to $24,999',
        4: [25000, 35000] #'$25,000 to $34,999',
        5: [35000, 50000] #'$35,000 to $49,999',
        6: [50000, 75000] #'$50,000 to $74,999',
        7: [75000, 100000] #'$75,000 to $99,999',
        8: [100000, 125000] #'$100,000 to $124,999',
        9: [125000, 150000] #'$125,000 to $149,999',
        10: [150000, 200000] #'$150,000 to $199,999',
        11: [200000, 400000] #'$200,000 or more'
    2009:
        -1: [0,0] # 'Appropriate Skip',
        -7: [0,0] # 'I prefer not to answer',
        -8: [0,0] # 'I do not know',
        -9: [0,0] # 'Not ascertained',
        1: [0, 5000] # '< $5,000',
        2: [5000, 10000] # '$5,000 - $9,999',
        3: [10000, 15000] # '$10,000 - $14,999',
        4: [15000, 20000] # '$15,000 - $19,999',
        5: [20000, 25000] # '$20,000 - $24,999',
        6: [25000, 30000] # '$25,000 - $29,999',
        7: [30000, 35000] # '$30,000 - $34,999',
        8: [35000, 40000] # '$35,000 - $39,999',
        9: [40000, 45000] # '$40,000 - $44,999',
        10: [45000, 50000] #    '$45,000 - $49,999',
        11: [50000, 55000] # '$50,000 - $54,999',
        12: [55000, 60000] # '$55,000 - $59,999',
        13: [60000, 65000] # '$60,000 - $64,999',
        14: [65000, 70000] # '$65,000 - $69,999',
        15: [70000, 75000] # '$70,000 - $74,999',
        16: [75000, 80000] # '$75,000 - $79,999',
        17: [80000, 100000] # '$80,000 - $99,999',
        18: [100000, 200000] # '$100,000 or more'
    2001:
        -1: [0,0] # 'Appropriate Skip',
        -7: [0,0] # 'I prefer not to answer',
        -8: [0,0] # 'I do not know',
        -9: [0,0] # 'Not ascertained',
        1: [0, 5000] # '< $5,000',
        2: [5000, 10000] # '$5,000 - $9,999',
        3: [10000, 15000] # '$10,000 - $14,999',
        4: [15000, 20000] # '$15,000 - $19,999',
        5: [20000, 25000] # '$20,000 - $24,999',
        6: [25000, 30000] # '$25,000 - $29,999',
        7: [30000, 35000] # '$30,000 - $34,999',
        8: [35000, 40000] # '$35,000 - $39,999',
        9: [40000, 45000] # '$40,000 - $44,999',
        10: [45000, 50000] #    '$45,000 - $49,999',
        11: [50000, 55000] # '$50,000 - $54,999',
        12: [55000, 60000] # '$55,000 - $59,999',
        13: [60000, 65000] # '$60,000 - $64,999',
        14: [65000, 70000] # '$65,000 - $69,999',
        15: [70000, 75000] # '$70,000 - $74,999',
        16: [75000, 80000] # '$75,000 - $79,999',
        17: [80000, 100000] # '$80,000 - $99,999',
        18: [100000, 200000] # '$100,000 or more'

ownership:
    default:
        -8: unknown # 'I do not know',
        -7: unknown #'I prefer not to answer',
        1: owned # 'Owned',
        2: rented # 'Rented',
        3: other # 'Other',
        91: other # 'Other'
        97: other
    2022:
        1: owned #'Owned',
        2: owned #'Owned',
        3: rented, # 'Rented',
        4: other

day:
    default:
        1: sunday
        2: monday
        3: tuesday
        4: wednesday
        5: thursday
        6: friday
        7: saturday


race1:
    default:
        -7: unknown
        -8: unknown
        -9: unknown
        -1: unknown
        1: white
        2: black
        3: asian
        4: other
        5: other
        6: other
        7: other
        97: other

race2:
    default:
        -7: unknown
        -8: unknown
        -9: unknown
        -1: unknown
        1: white
        2: black
        3: asian
        4: other
        5: other
        6: other
        7: other
        8: other
        9: other
        10: other
        11: other
        12: other
        13: other
        14: other
        15: other
        16: other
        17: other
        97: other

'FLAG100': {'default': {1: 'All eligible household members completed',
    2: '75% to 99% of eligible household members completed'}}
'HBPPOPDN': {
    'default': {-9: 'Not ascertained',
        50: '0-99',
        300: '100-499',
        750: '500-999',
        1500: '1,000-1,999',
        3000: '2,000-3,999',
        7000: '4,000-9,999',
        17000: '10,000-24,999',
        30000: '25,000-999,999'},
    2022: {-9: 'Not ascertained',
        1: '0-99',
        2: '100-499',
        3: '500-999',
        4: '1,000-1,999',
        5: '2,000-3,999',
        6: '4,000-9,999',
        7: '10,000-24,999',
        8: '25,000-999,999'}
        }
'CDIVMSAR': {'default': {11: 'New England MSA/CMSA of 1 million+ with heavy rail',
    12: 'New England MSA/CMSA of 1 million+ w/o heavy rail',
    13: 'New England MSA of less than 1 million',
    14: 'New England Not in an MSA',
    21: 'Mid-Atlantic MSA/CMSA of 1 million+ with heavy rail',
    22: 'Mid-Atlantic MSA/CMSA of 1 million+ w/o heavy rail',
    23: 'Mid-Atlantic MSA of less than 1 million',
    24: 'Mid-Atlantic Not in an MSA',
    31: 'East North Central MSA/CMSA of 1 million+ with heavy rail',
    32: 'East North Central MSA/CMSA of 1 million+ w/o heavy rail',
    33: 'East North Central MSA of less than 1 million',
    34: 'East North Central Not in an MSA',
    42: 'West North Central MSA/CMSA of 1 million+ w/o heavy rail',
    43: 'West North Central MSA of less than 1 million',
    44: 'West North Central Not in an MSA',
    51: 'South Atlantic MSA/CMSA of 1 million+ with heavy rail',
    52: 'South Atlantic MSA/CMSA of 1 million+ w/o heavy rail',
    53: 'South Atlantic MSA of less than 1 million',
    54: 'South Atlantic Not in an MSA',
    62: 'East South Central MSA/CMSA of 1 million+ w/o heavy rail',
    63: 'East South Central MSA of less than 1 million',
    64: 'East South Central Not in an MSA',
    72: 'West South Central MSA/CMSA of 1 million+ w/o heavy rail',
    73: 'West South Central MSA of less than 1 million',
    74: 'West South Central Not in an MSA',
    82: 'Mountain MSA/CMSA of 1 million+ w/o heavy rail',
    83: 'Mountain MSA of less than 1 million',
    84: 'Mountain Not in an MSA',
    91: 'Pacific MSA/CMSA of 1 million+ with heavy rail',
    92: 'Pacific MSA/CMSA of 1 million+ w/o heavy rail',
    93: 'Pacific MSA of less than 1 million',
    94: 'Pacific Not in an MSA'}}
'HBHTNRNT': {'default': {1: '0-4%',
    5: '5-14%',
    20: '15-24%',
    30: '25-34%',
    40: '35-44%',
    50: '45-54%',
    60: '55-64%',
    70: '65-74%',
    80: '75-84%',
    90: '85-94%',
    95: '95-100%'}}
'URBAN': {'default': {1: 'In an urban area',
    2: 'In an Urban cluster',
    3: 'In an area surrounded by urban areas',
    4: 'Not in urban area'}}
'HTRESDN': {'default': {-9: 'Not ascertained',
    1: '0-99',
    2: '100-499',
    3: '500-999',
    4: '1,000-1,999',
    5: '2,000-3,999',
    6: '4,000-9,999',
    7: '10,000-24,999',
    8: '25,000-999,999'}}
'HBRESDN': {'default': {-9: 'Not ascertained',
    1: '0-99',
    2: '100-499',
    3: '500-999',
    4: '1,000-1,999',
    5: '2,000-3,999',
    6: '4,000-9,999',
    7: '10,000-24,999',
    8: '25,000-999,999'}}
'HHFAMINC': {
    'default': {-7: 'I prefer not to answer',
    -9: 'Not ascertained',
    -8: 'I do not know',
    1: 'Less than $10,000',
    2: '$10,000 to $14,999',
    3: '$15,000 to $24,999',
    4: '$25,000 to $34,999',
    5: '$35,000 to $49,999',
    6: '$50,000 to $74,999',
    7: '$75,000 to $99,999',
    8: '$100,000 to $124,999',
    9: '$125,000 to $149,999',
    10: '$150,000 to $199,999',
    11: '$200,000 or more'},
    2022: {-7: 'I prefer not to answer',
    -8: 'I do not know',
    1: 'Less than $10,000',
    2: '$10,000 to $14,999',
    3: '$15,000 to $24,999',
    4: '$25,000 to $34,999',
    5: '$35,000 to $49,999',
    6: '$50,000 to $74,999',
    7: '$75,000 to $99,999',
    8: '$100,000 to $124,999',
    9: '$125,000 to $149,999',
    10: '$150,000 to $199,999',
    11: '$200,000 or more'}}
'HOMETYPE': {'default': {1: 'One-family detached',
    2: 'One-family attached (townhome, condo)',
    3: 'Building with 2 or more apartments',
    4: 'Mobile home',
    5: 'Boat, RV, van, etc.'}}
'HTEEMPDN': {'default': {-9: 'Not ascertained',
    1: '0-49',
    2: '50-99',
    3: '100-249',
    4: '250-499',
    5: '500-999',
    6: '1,000-1,999',
    7: '2,000-3,999',
    8: '4,000-999,999'}}
'MSACAT': {'default': {1: 'MSA of 1 million or more, with rail',
    2: 'MSA of 1 million or more, without rail',
    3: 'MSA less than 1 million',
    4: 'Not in MSA'}}
'HTPPOPDN': {'default': {-9: 'Not ascertained',
    1: '0-99',
    2: '100-499',
    3: '500-999',
    4: '1,000-1,999',
    5: '2,000-3,999',
    6: '4,000-9,999',
    7: '10,000-24,999',
    8: '25,000-999,999'}}
'HH_HISP': {'default': {1: 'Hispanic or Latino', 2: 'Not Hispanic or Latino'}}
'HOMEOWN': {
    'default': {
        -8: 'I do not know',
        -7: 'I prefer not to answer',
        1: 'Owned',
        2: 'Rented',
        97: 'Other',
        },
    2022: {
        1: 'Owned',
        2: 'Owned',
        3: 'Rented',
        4: 'Other'}
    }
'LIF_CYC': {
    'default': {
        -9: 'Not ascertained',
        1: 'one adult, no children',
        2: '2+ adults, no children',
        3: 'one adult, youngest child 0-5',
        4: '2+ adults, youngest child 0-5',
        5: 'one adult, youngest child 6-15',
        6: '2+ adults, youngest child 6-15',
        7: 'one adult, youngest child 16-21',
        8: '2+ adults, youngest child 16-21',
        9: 'one adult, retired, no children',
        10: '2+ adults, retired, no children'
        }
    }
'MSASIZE': {'default': {1: 'In an MSA of Less than 250,000',
    2: 'In an MSA of 250,000 - 499,999',
    3: 'In an MSA of 500,000 - 999,999',
    4: 'In an MSA or CMSA of 1,000,000 - 2,999,999',
    5: 'In an MSA or CMSA of 3 million or more',
    6: 'Not in MSA or CMSA'}}
'URBANSIZE': {'default': {1: '50,000-199,999',
    2: '200,000-499,999',
    3: '500,000-999,999',
    4: '1,000,000 or more with heavy rail',
    5: '1,000,000 or more without heavy rail',
    6: 'Not in urbanized area'}}
'TRAVDAY': {'default': {1: 'Sunday',
    2: 'Monday',
    3: 'Tuesday',
    4: 'Wednesday',
    5: 'Thursday',
    6: 'Friday',
    7: 'Saturday'}}
'CENSUS_D': {'default': {1: 'New England',
    2: 'Middle Atlantic',
    3: 'East North Central',
    4: 'West North Central',
    5: 'South Atlantic',
    6: 'East South Central',
    7: 'West South Central',
    8: 'Mountain',
    9: 'Pacific'}}
'HBHUR': {'default': {1: 'Rural',
    2: 'Small Town',
    3: 'Second City',
    4: 'Suburban',
    5: 'Urban'}}
'CENSUS_R': {'default': {1: 'Northeast', 2: 'Midwest', 3: 'South', 4: 'West'}}
'HHRELATD': {'default': {1: 'At least two persons in hh are related',
    2: 'No related persons in hh'}}
'URBRUR_2010': {'default': {1: 'Urban', 2: 'Rural', -9: 'Not ascertained'}}
'HTHTNRNT': {'default': {1: '0-4%',
    5: '5-14%',
    20: '15-24%',
    30: '25-34%',
    40: '35-44%',
    50: '45-54%',
    60: '55-64%',
    70: '65-74%',
    80: '75-84%',
    90: '85-94%',
    95: '95-100%'}}
'URBRUR': {'default': {1: 'Urban', 2: 'Rural'}}
'RAIL': {'default': {1: 'Yes', 2: 'No'}}
'HHFAMINC_IMP': {'default': {1: 'Less than $10,000',
    2: '$10,000 to $14,999',
    3: '$15,000 to $24,999',
    4: '$25,000 to $34,999',
    5: '$35,000 to $49,999',
    6: '$50,000 to $74,999',
    7: '$75,000 to $99,999',
    8: '$100,000 to $124,999',
    9: '$125,000 to $149,999',
    10: '$150,000 to $199,999',
    11: '$200,000 or more'
    }
}