column_mappings: {
    "PERSONID": "pid", # id within household
    "HOUSEID": "hid",
    "R_AGE": "age",
    "EDUC": "education",
    "MEDCOND": "disability",  # actually difficulty travelling
    "PRMACT": "employment",
    "R_RELAT": "relationship",
    "R_SEX": "sex",
    "DRIVER": "has_licence",  # actually derived
    "HBHUR": "rurality",
    }

"education":
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        -1: "unknown",
        1: "none",
        2: "school",
        3: "school",
        4: "undergraduate",
        5: "graduate",
    }
    2022: {
        -1: "unknown",
        1: "none",
        2: "none",
        3: "school",
        4: "undergraduate",
        5: "undergraduate",
        6: "undergraduate",
        7: "graduate",
        8: "graduate",
    }
    2001: {
        -8: "unknown",
        -7: "unknown",
        -1: "unknown",
        -9: "unknown",
        1: "none",
        2: "school",
        3: "school",
        4: "school",
        5: "undergraduate",
        6: "undergraduate",
        7: "undergraduate",
        8: "graduate",
    }
"disability":
    "default": {
        -1: "unknown",
        -7: "unknown",
        -8: "unknown",
        -9: "unknown",
        1: "yes",
        2: "no",
    }
"employment":
    2022: {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        -1: "employed",
        1: "unemployed",
        2: "unemployed",
        3: "unemployed",
        4: "education",
        5: "retired",
        97: "other",
    }
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        -1: "unknown",
        1: "employed",
        2: "employed",
        3: "unemployed",
        4: "home",
        5: "education",
        6: "retired",
        7: "other",
        97: "other",
    }
"race":
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        1: "white",
        2: "black",
        3: "asian",
        4: "american_native",
        5: "american_native",
        6: "other",
        97: "other",
    }
"relationship":
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        1: "self",
        2: "spouse/partner",
        3: "child",
        4: "parent",
        5: "sibling",
        6: "other",
        7: "spouse/partner",
        8: "other",
    }
    2017: {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        1: "self",
        2: "spouse/partner",
        3: "child",
        4: "parent",
        5: "sibling",
        6: "other",
        7: "other",
    }
    2022: {
        -9: "unknown",
        1: "spouse/partner",
        2: "child",
        3: "parent",
        4: "sibling",
        5: "other",
        6: "other",
        7: "self",
    }
"sex":
    "default": {
        -7: "unknown",
        -8: "unknown",
        -9: "unknown",
        1: "male",
        2: "female",
    }
"has_licence":
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        -1: "unknown",
        1: "yes",
        2: "no",
    }
rurality:
    default:
        -9: unknown
        1: rural
        2: suburban
        3: urban
        4: suburban
        5: urban
